apiVersion: v1
kind: Pod
metadata:
  name: implicit
spec:
  containers:
  - args: [ sample-signal-pass ]
    image: cirocosta/sample-signal-pass:with-signal-defined
    imagePullPolicy: Always
    name: with
  - args: [ sample-signal-pass ]
    image: cirocosta/sample-signal-pass:without-signal-defined
    imagePullPolicy: Always
    name: without
